# Generated by Django 2.1 on 2019-03-08 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordmeaning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='one_word',
            new_name='your_word',
        ),
        migrations.AlterField(
            model_name='word',
            name='word_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 18, 55, 44, 472560)),
        ),
    ]
