# Generated by Django 2.1 on 2019-06-10 04:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordmeaning', '0003_auto_20190308_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 10, 38, 9, 301474)),
        ),
    ]
